apiVersion: v1
kind: Service
metadata:
  name: greenapi-service
  namespace: greenapi
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: greenapi
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: greenapi-deployment
  namespace: greenapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: greenapi
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: greenapi
    spec:
      containers:
      - image: registry.gitlab.com/greenapi1/nuxt-greenapi/greenapi
        name: greenapi
        ports:
        - containerPort: 80
          name: http
        imagePullPolicy: Always
        env:
        - name: TZ
          value: Europe/Moscow
      imagePullSecrets:
        - name: greenapicred
---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: greenapi-ingress
  namespace: greenapi
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-production"
    nginx.ingress.kubernetes.io/from-to-www-redirect: "true"
spec:
  ingressClassName: nginx
  rules:
    - host: greenapi.it-integ.ru
      http:
        paths:
        - pathType: Prefix
          backend:
            service:
              name: greenapi-service
              port:
                number: 80
          path: "/"
  tls:
    - hosts:
      - greenapi.it-integ.ru
      secretName: greenapi-tls
